[build]
command = "npm install && npm run build"
output_directory = "build"

[build.environment]
NODE_VERSION = "18"
NODE_ENV = "production"

[build.settings]
entry_point = "build/index.html"
build_directory = "build"

[site]
bucket = "build"
entry-point = "index.html"

[pages]
build_command = "npm install && npm run build"
build_output_directory = "build"
entry_point = "build/index.html"

[pages.environment]
NODE_VERSION = "18"
NODE_ENV = "production"
