[build]
command = "npm install && npm run build"
output_directory = "build"

[site]
bucket = "build"
entry-point = "index.html"

[build.environment]
NODE_VERSION = "18"

# Pages-specific configuration
pages_build_output_dir = "build"
